spring.application.name=tabletopserv
spring.profiles.default=dev

tabletopserv.app.base-url=${APP_BASE_URL:http://localhost:8080}
tabletopserv.jwt.secret=${JWT_SECRET:JtCeUaD41EV9iI+WoPojPt0Llx3L46tk4lSra9ttjo5a88nzHJMNLZZELKkN3Qgc}
tabletopserv.jwt.expiration-millis=${JWT_EXPIRATION:86400000}
tabletopserv.verification.token-ttl-millis=${VERIFY_TTL:86400000}
tabletopserv.verification.resend-cooldown-millis=${RESEND_COOLDOWN:60000}
tabletopserv.admin.username=${ADMIN_USERNAME:admin}
tabletopserv.admin.email=${ADMIN_EMAIL:admin@tabletop.local}
tabletopserv.admin.password=${ADMIN_PASSWORD:AdminPassw0rd!}